#!/usr/bin/env bash

set -e

NAME=zclone-serve-ftp
USER=zclone
PASS=FuddleIdlingJell5
IP=127.0.0.1
PORT=28622

start() {
    run zclone serve ftp --user $USER --pass $PASS --addr ${IP}:${PORT} ${DATADIR}
    
    echo type=ftp
    echo host=${IP}
    echo port=$PORT
    echo user=$USER
    echo pass=$(zclone obscure $PASS)
    echo _connect=${IP}:${PORT}
}

. $(dirname "$0")/zclone-serve.bash
