#!/usr/bin/env bash

set -e

NAME=zclone-hdfs
KERBEROS=${KERBEROS-"false"}

. $(dirname "$0")/docker.bash

start() {
    docker run --rm -d --name "zclone-hdfs" \
        --hostname "zclone-hdfs" \
        -e "KERBEROS=$KERBEROS"  \
        -p 127.0.0.1:9866:9866   \
        -p 127.0.0.1:8020:8020   \
        -p 127.0.0.1:750:750     \
        -p 127.0.0.1:88:88       \
        zclone/test-hdfs
    sleep 30

    if [ $KERBEROS = "true" ]; then
        docker cp zclone-hdfs:/tmp/krb5cc_0 /tmp/krb5cc_`id -u`
    fi

    echo type=hdfs
    echo namenode=127.0.0.1:8020
    echo username=root
    echo _connect=127.0.0.1:8020
}

. $(dirname "$0")/run.bash
