#!/usr/bin/env bash

set -e

NAME=zclone-serve-s3
ACCESS_KEY_ID=zclone
SECRET_ACCESS_KEY=JoltRogueVerde5
IP=127.0.0.1
PORT=28624

start() {
    run zclone serve s3 --auth-key ${ACCESS_KEY_ID},${SECRET_ACCESS_KEY} --addr ${IP}:${PORT} ${DATADIR}
    
    echo type=s3
    echo provider=Zclone
    echo endpoint=http://${IP}:${PORT}/
    echo access_key_id=${ACCESS_KEY_ID}
    echo secret_access_key=${SECRET_ACCESS_KEY}
    echo _connect=${IP}:${PORT}
}

. $(dirname "$0")/zclone-serve.bash
