#!/usr/bin/env bash

set -e

NAME=vsftpdtls
USER=zclone
PASS=TiffedRestedSian4

. $(dirname "$0")/docker.bash

start() {
    docker run --rm -d --name $NAME \
           -e "FTP_USER=zclone" \
           -e "FTP_PASS=$PASS" \
           zclone/vsftpd

    echo type=ftp
    echo host=$(docker_ip)
    echo user=$USER
    echo pass=$(zclone obscure $PASS)
    echo writing_mdtm=true
    echo encoding=Ctl,LeftPeriod,Slash
    echo _connect=$(docker_ip):21
}

. $(dirname "$0")/run.bash
