zclone-dlna-server:
  container_name: zclone-dlna-server

  image: zclone/zclone
  command:
# Tweak here zclone's command line switches:
#    - "--config"
#    - "/path/to/mounted/zclone.conf"
    - "--verbose"
    - "serve"
    - "dlna"
    - "remote:/"
    - "--name"
    - "myDLNA server"
    - "--read-only"
#    - "--no-modtime"
#    - "--no-checksum"

  restart: unless-stopped

  # Use host networking for simplicity with DLNA broadcasts
  # and to avoid having to do port mapping.
  net: host

  # Here you have to map your host's zclone.conf directory to
  # container's /root/.config/zclone/ dir (R/O).
  # If you have any remote referencing local files, you have to
  # map them here, too.
  volumes:
    - ~/.config/zclone/:/root/.config/zclone/:ro
